AWSTemplateFormatVersion: "2010-09-09"
Description: Create an EC2 instance with a Security Group

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # ⚠️ Update this for better 

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: 9.30AM-PASS
      ImageId: ami-0d03cb826412c6b0f  # Amazon Linux 2 AMI (example, region-specific)
      SecurityGroups:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: CFN-EC2-Instance

